### ISSUE TITLE
How to edit and add to HTML autocompletions in ST3?

### ISSUE THREAD

**Issue by DavidCheshire** [guillermooo/sublime-undocs#105]
I would like to edit and add to the HTML completions in ST3 but I am struggling to find out how to do it.

I created an HTML.sublime-completions file in my User folder, but when I added some completions that started with the reserved character < and added "auto_complete_triggers": [ {"selector": "text.html", "characters": "&<"} ], in my Preferences.sublime-settings, the HTML completions built into ST3 (which I think depend on the < character) stopped working. 

I read that the built in autocompletions are contained in the HTML.sublime-package in the packages folder under the folder that ST3 itself is installed in, so I copied this and extracted the files within it, which are:

Comments.tmPreferences
encode_html_entities.py
html.sublime-snippet
HTML.tmLanguage
html_completions.py
Miscellaneous.tmPreferences
Symbol List - ID.tmPreferences

But when I studied these I was not sure which one I needed to edit, or where to put the edited file - or do I need to put all the files somewhere? Can you give any hints or point to documentation on how to edit and add to the HTML autocompletions that are built into ST3?

Thanks for any help.

Kind regards - David

**Comment by FichteFoll** [comment]
I haven't messed with the HTML package in a while, but iirc the html completions were provided by a plugin, `html_completions.py` respectively. You might want to look into that file.

Fortunately there are docs available on this topic:
http://docs.sublimetext.info/en/latest/extensibility/plugins.html#another-plugin-example-feeding-the-completions-list
http://docs.sublimetext.info/en/latest/reference/api.html#sublime_plugin.EventListener.on_query_completions

**Comment by DavidCheshire** [comment]
Thanks for getting back to me. The html_completions.py file certainly looks promising. Once I have edited it, what should I do with it, put it into my /packages/user folder?

BTW I looked at the documents you listed but at my stage of knowledge they don't really convey anything to me, something simpler would be appreciated. I know they seem easy to understand once you understand them, but coming to them as a novice is like reading a foreign language for the first time.

Thanks for your help!

Kind regards - David

**Comment by FichteFoll** [comment]
Put it into `Packages/HTML`, it will then override the archived version and get loaded instead.

If you are not familiar with Python, the ST API docs are not a place to learn it. Check out http://learnpythonthehardway.org/ (which is more suited for absolute beginners) or google for a small introduction tutorial more of your liking.

**Comment by DavidCheshire** [comment]
Editing the html_completions.py file and saving it in ~/Packages/HTML worked perfectly, thanks.

Kind regards - David
