### ISSUE TITLE
Where do I go to edit my completions in sublime text 3 on mac

### ISSUE THREAD

**Issue by jrdn91** [guillermooo/sublime-undocs#16]
I'm still new to mac osx here and I for the life of me can't find it on my own or on google where I go to edit those files. How do I find them so I can edit my completions? Sorry if this is a basic question.

**Comment by FichteFoll** [comment]
https://www.sublimetext.com/docs/3/packages.html

It should probably be added to the docs if it hasn't been already.

**Comment by jrdn91** [comment]
Yeah I don't see anything there that gives me the path to the completion files.

**Comment by guillermooo** [comment]
It wouldn't hurt to make a general reference to the usual location for user-created resources somewhere —probably in _Basic Concepts_— and then mention it again in each topic related to resources, like completion files.

@Jordan4jc To answer your question, _.sublime-completions_ files created by the current user are usually placed either under _Packages/User_ or under a specific package folder in _Packages_ if it makes sense. Such files provided by packages created by others may originate in _.sublime-package_ files located under _Installed Packages_ instead .

Packages shipped with ST have their home under _Packages_, next to the executable. Arguably, ST3 has made things a little bit more confusing with so many options. I would stick to the data folder and use subfolders under _Packages_ if you have no good reason to use _.sublime-package_ files. These are simply tidier for distribution, but many (most?) packages out there don't use them...

If you feel up to it, it would be good to add some of this info to the docs.

**Comment by DavidCheshire** [comment]
Like the OP I would like to edit and add to the HTML completions in ST3 but I am struggling to find out how to do it. I created an HTML.sublime-completions file in my User folder, but when I tried to add some completions that started with the reserved character < the HTML completions built into ST3 stopped working. Can you give any hints on how I do this?

Kind regards - David

**Comment by FichteFoll** [comment]
@DavidCheshire HTML completions are dynamically generated by a Python plugin. I don't exactly know what you did, but this is not really a place for support. Please try asking in the forums.
