### ISSUE TITLE
Selecting Blocks in sublime on Linux doesn't work

### ISSUE THREAD

**Issue by rubo77** [guillermooo/sublime-undocs#180]
This doesn't seem to work:

https://github.com/guillermooo/sublime-undocs/blame/sublime-text-3/source/editing/editing.rst#L55

When I try this I just get the right mouse button menu

**Comment by rubo77** [comment]
Please add some hint like "Use SHIFT+ALT + Up/Down key to create a block selection"

**Comment by FichteFoll** [comment]
According to `Default (Linux).sublime-mousmap`, it should work:

``` json
    {
        "button": "button2", "modifiers": ["shift"],
        "press_command": "drag_select",
        "press_args": {"by": "columns"}
    },
```

Also, alt+shift+up/down is mentioned [just below that](https://github.com/guillermooo/sublime-undocs/blame/sublime-text-3/source/editing/editing.rst#L74).

**Comment by rubo77** [comment]
What could be wrong if none of these combinations work any more on Ubuntu?

The only one working is CTRL Shift L to split selection.

**Comment by FichteFoll** [comment]
Well, they can both be overridden by packages. Try with all packages disabled.
