### ISSUE TITLE
Color scheme shadow info and typo

### ISSUE THREAD

**Issue by keith-hall** [guillermooo/sublime-undocs#193]
Hi,

I realize this documentation isn't maintained at the moment, but thought I would log this for people that are interested.

The text at http://docs.sublimetext.info/en/latest/reference/color_schemes.html#shadow isn't very descriptive.

It seems that the shadow is visible when the text in the document is wider than the window, and will appear on the left and/or the right, depending whether the view can be scrolled to the left or the right.

Also, there is a typo at `shadowWidth`

> Width o**t** the shadow effect when the buffer is scrolled.

and setting it like this:

```
<key>shadowWidth</key>
<string>42</string>
```

seems to remove the shadow altogether, so maybe some example values could be provided? Otherwise it seems that the shadow only appears when this key doesn't exist in the tmTheme file.

**Comment by FichteFoll** [comment]
Thanks for the report. That wording is really poor and I imagine some screenshots would do wonders on that page. 

`shadowWidth` works fine for me, up to a value of `32`. `33` or higher makes the shadow disappear, which matches what I tested some time ago.

![2016-04-21_14 43 05](https://cloud.githubusercontent.com/assets/931051/14709167/76d6dd20-07cf-11e6-97b2-c936f25852ca.png)

**Comment by FichteFoll** [comment]
Fixed by 9dd40dc52e0c4a5ae78cccf21c4dba1c93b056ae.

**Comment by borela** [comment]
Why doesn't the shadow disappear when we set it to 0? Bug?

**Comment by FichteFoll** [comment]
Seems like it. It disappears for me if I set it to 1 however.

**Comment by keith-hall** [comment]
why set it to 0 in a color scheme as opposed to setting `"draw_minimap_border": false` in the user prefs?

**Comment by borela** [comment]
The border was already false but shadow kept appearing when the two scrollbars were visible.

**Comment by keith-hall** [comment]
ah sorry, you're right, that preference seems to control something else - my bad. Somehow I was convinced I'd seen a setting for this though...

**Comment by borela** [comment]
I was confused about this too for a long time :s and thank you, it was only when I found your thread that I got it fixed.

**Comment by keith-hall** [comment]
[Here we go, apparently there is an undocumented setting `draw_shadows` that can be set to false](http://thume.ca/2016/12/03/disassembling-sublime-text/), as an alternative to setting the `shadowWidth` in the color scheme :)
and you're welcome, I posted this here so that people with the same problem would find a solution so I'm glad it helped :)

**Comment by borela** [comment]
The `draw_shadows` worked :D that's a way better than having it in the color scheme thank you.

**Comment by FichteFoll** [comment]
Ah sorry, I meant to mention the `draw_shadows` setting (although I didn't remember its exact name) but was more concerned about how we should convey this odd behavior with 0 and 1 in our docs that I forgot.

**Comment by keith-hall** [comment]
I've [logged it as an issue on the Core issues repo](https://github.com/SublimeTextIssues/Core/issues/1607), maybe it will get added in a future build so that people know of it's existence ;)

**Comment by FichteFoll** [comment]
We also have a card about it in our trello board. I'm making sure that whatever I find that is not documented, I add to some list so we don't forget about it.

Lists are my secret strength.

**Comment by keith-hall** [comment]
I should probably check out that Trello board more often ;) so many times I've logged things here that are probably already on there...

**Comment by FichteFoll** [comment]
Note that we also have an internal board that hasnt been sorted into the public board yet, so you'll still miss things even if you look at the public one first. 😉
