### ISSUE TITLE
Command Line examples

### ISSUE THREAD

**Issue by keith-hall** [guillermooo/sublime-undocs#201]
Hi,

The [command line usage page](http://docs.sublimetext.info/en/latest/command_line/command_line.html) is very lacking in detail and examples.

I think it would be great to include details on how the `--command` argument to `subl` works, [as mentioned on the ST3 forums recently](https://forum.sublimetext.com/t/is-there-any-applescript-or-literally-any-language-support-for-accessing-the-python-console-from-outside-sublime/19930/7) - specifically, how to execute multiple commands at once and how to pass arguments (in JSON) to the commands.

**Comment by FichteFoll** [comment]
Certainly :smile: 

![2016-05-13_13 23 29](https://cloud.githubusercontent.com/assets/931051/15246553/f57e415a-190d-11e6-97e5-860f600d74c9.png)

**Comment by guillermooo** [comment]
#203
