### ISSUE TITLE
Mac Keyboard Symbols not rendered with Chrome on Mac OS X

### ISSUE THREAD

**Issue by sumnermic** [guillermooo/sublime-undocs#216]
Hello,

I'm not seeing the symbols properly whilst using Mac OSX Chrome Version 51.0.2704.106 (64-bit).

It is working good on Firefox and Safari though.

Please see screenshot below.

![image](https://cloud.githubusercontent.com/assets/12336032/16545294/712b9658-411e-11e6-94bb-5780321ebcb1.png)

Kind regards,

sumnermic

**Comment by FichteFoll** [comment]
This is a problem with Chrome's font rendering. I don't think there is anything we can do here besides not using the symbols at all, which is not something I'm comfortable with.

It works on my Windows machine, btw.

**Comment by guillermooo** [comment]
Works fine for me too. @sumnermic are you using UTF-8 encoding?

Double-checked on a Mac.

**Comment by sumnermic** [comment]
I'm using UTF-8 on Chrome.

However I'd like to clarify if it's entirely a Chrome issue?

I get the same symbols rendered incorrectly on Chrome Canary.

**Comment by sumnermic** [comment]
**I found a workable solution:**

`Font-family: 'Lato';` renders text properly but not the symbols, that's why the fall-back fonts don't take place.
So if we change it to 'Helvetica Neue' instead, it renders properly.

Proxima Nova `'proxima-nova'` doesn't seem to do anything for me? Has it been linked as a source properly. Or else it depends on if it's available on the User's Fonts directory?

**Comment by guillermooo** [comment]
It seems to be a config issue. The symbols render fine for me on Chrome for OS X for me. I'm using all the defaults. You could try changing the fonts, for example.

**Comment by sumnermic** [comment]
I'd like to know where I can change the config if possible? It works properly when I fall-back to 'Helvetica Neue'. Sorry you couldn't replicate the issue.
