### ISSUE TITLE
Possible to enter license key from bash?

### ISSUE THREAD

**Issue by jfairchild** [guillermooo/sublime-undocs#22]
Ultimately, I'd like to enter my company's license key via `boxen`. Is there a way to enter the key with `subl` or by editing some config file? Thanks.

**Comment by FichteFoll** [comment]
The license is saved in `Data/Local/License.sublime_license` (ST3) and `Data/Settings/License.sublime_license` (ST2). When you enter the license via the menu item it will be hashed with your machine id or whatever so you don't accidentally share it with others, but you can also put the literal license there. You should know what the `Data/` dir refers to.

**Comment by jfairchild** [comment]
Worked like a charm. Thank you.
