### ISSUE TITLE
What's the font family of screenshot?

### ISSUE THREAD

**Issue by richellyitalo** [guillermooo/sublime-undocs#237]
Please anything know what is the font family of screenshot?
![image](https://cloud.githubusercontent.com/assets/1899604/25003004/a5bc76dc-2023-11e7-9555-9e0032bd52dc.png)

**Comment by aziz** [comment]
consolas

**Comment by richellyitalo** [comment]
Thanks @aziz

**Comment by FichteFoll** [comment]
Which is the default font on Windows, FWIW.
