### ISSUE TITLE
Replace text on selection get deselected

### ISSUE THREAD

**Issue by Perhelion** [guillermooo/sublime-undocs#259]
There is something annoying. If we put on the option "In selection" the selection get deselected!

Sorry but for me personally this is the most disadvantage (there are some more), as I'm not used to it from any other editor I used before.

PS: And where is the amount of replacements displayed?

Thanks for the nice editor.

**Comment by FichteFoll** [comment]
You were probably looking for the repository https://github.com/SublimeTextIssues/Core, where issues with ST itself are reported. This repo here is only about the unofficial documentation website at http://docs.sublimetext.info/en/latest/.

There is already a ticket for the issue you describe: https://github.com/SublimeTextIssues/Core/issues/191

Amount (or number) of replacements/matches is displayed in the status bar.
