### ISSUE TITLE
[transferred] Error in documentation

### ISSUE THREAD

**Issue by guillermooo** [guillermooo/sublime-undocs#46]
Sublime Text 2 does not recognize the keywords `env` or `shell` in build systems: http://sublimetext.userecho.com/topic/125307-build-system-should-honor-env-as-documented/

The page https://github.com/SublimeText/UnofficialDocs/blob/master/source/reference/build_systems.rst should be modified accordingly.

**Comment by FichteFoll** [comment]
Both parameters are accepted by the ST2 and ST3 `exec` command (as of their latest releases), I just checked their sources.

I think this is a non-issue. Maybe they were using plugins that overrode the original file or were using old versions.
