### ISSUE TITLE
First "cmd" does not work in build system.

### ISSUE THREAD

**Issue by unrevised6419** [guillermooo/sublime-undocs#5]
Building system

{
    "cmd": ["TASM", "$file_name"],
    "cmd": ["TLINK", "/t", "$file_base_name.OBJ"],
    "selector": "source.asm"
}

first line is not executing
second line, the TLINK needs a file created by TASM
but it gives me error that file not exist (really not exist)
if i put thoose two on different build systems
and run them consecutively it works

this problem have a solution?
thx in advance!

**Comment by guillermooo** [comment]
If you're looking for general support, this is not the best place: you should try the official forums instead.

In any case, what you're trying to do isn't possible. 'cmd' must be a single key; you can't have multiple 'cmd' in the same build system. My suggestiong would be to try moving the commands to a script file and calling the script with the desired arguments.

**Comment by unrevised6419** [comment]
ok, thx
