### ISSUE TITLE
is there any method in api to change active window?

### ISSUE THREAD

**Issue by thecotne** [guillermooo/sublime-undocs#74]
i am making sublime package and it has a web server and listens to some port and gets some commands from browser 
first command i want to make is `open file` 
so i am getting file path opening file but sublime text window not getting active 
i found that i can execute sublime_text.exe  in shell and sublime text window gets activated but how to chose which window to get active

**Comment by FichteFoll** [comment]
See https://github.com/SublimeText/Issues/issues/444.
