### ISSUE TITLE
Delete old_fixes branch

### ISSUE THREAD

**Issue by guillermooo** [guillermooo/sublime-undocs#80]
cc @FichteFoll 

I think we can get rid of this one?

https://github.com/guillermooo/sublime-undocs/tree/old_fixes

**Comment by FichteFoll** [comment]
I'd prefer to keep it at least somewhere, just in case we'd need to go back to it at some point (since we didn't merge it the usual way). Branches are not expensive, and especially not in this small project.

**Comment by guillermooo** [comment]
ok
